version: '2.4'

services:
  api:
    build:
      context: .
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/vetting-nodejs
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:4.4.6-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
